/*RETAIL ANALYTICS PROJECT  */
--  SQL ANALYSIS QUERIES 

/*  SALES OVERVIEW */

-- Total Revenue (only successful payments)
SELECT 
    SUM(amount) AS total_revenue
FROM payments
WHERE payment_status = 'Successful';

--  Total Number of Orders
SELECT 
    COUNT(*) AS total_orders
FROM orders;

--  Average Order Value
SELECT 
    SUM(amount) / COUNT(DISTINCT order_id) AS avg_order_value
FROM payments
WHERE payment_status = 'Successful';

--  Total Units Sold
SELECT 
    SUM(quantity) AS total_units_sold
FROM order_items;

--  Monthly Revenue Trend
SELECT 
    YEAR(payment_date) AS year,
    MONTH(payment_date) AS month,
    SUM(amount) AS monthly_revenue
FROM payments
WHERE payment_status = 'Successful'
GROUP BY YEAR(payment_date), MONTH(payment_date)
ORDER BY year, month;

--  Monthly Order Count
SELECT 
    YEAR(order_date) AS year,
    MONTH(order_date) AS month,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY year, month;


/* PRODUCT PERFORMANCE ANALYSIS */

--  Top Selling Products by Quantity
SELECT 
    p.product_id,
    p.product_name,
    SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN product p ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_sold DESC;

--  Revenue Generated by Each Product
SELECT 
    p.product_id,
    p.product_name,
    SUM(oi.quantity * oi.price_at_purchase) AS revenue
FROM order_items oi
JOIN product p ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY revenue DESC;

--  Low Stock Products
SELECT 
    product_id,
    product_name,
    stock_quantity
FROM product
WHERE stock_quantity < 10
ORDER BY stock_quantity ASC;

--  Products with Highest Profit Margin per Unit
SELECT 
    product_id,
    product_name,
    price,
    cost_price,
    (price - cost_price) AS profit_per_unit
FROM product
ORDER BY profit_per_unit DESC;

--  Total Profit by Product
SELECT 
    p.product_id,
    p.product_name,
    SUM((oi.price_at_purchase - p.cost_price) * oi.quantity) AS total_profit
FROM order_items oi
JOIN product p ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_profit DESC;

--  Product-wise Order Count
SELECT 
    p.product_id,
    p.product_name,
    COUNT(DISTINCT oi.order_id) AS order_count
FROM order_items oi
JOIN product p ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY order_count DESC;


/* 3. CATEGORY ANALYSIS */

--  Revenue by Category
SELECT 
    c.category_id,
    c.category_name,
    SUM(oi.quantity * oi.price_at_purchase) AS revenue
FROM order_items oi
JOIN product p ON oi.product_id = p.product_id
JOIN category c ON p.category_id = c.category_id
GROUP BY c.category_id, c.category_name
ORDER BY revenue DESC;

--  Units Sold by Category
SELECT 
    c.category_id,
    c.category_name,
    SUM(oi.quantity) AS units_sold
FROM order_items oi
JOIN product p ON oi.product_id = p.product_id
JOIN category c ON p.category_id = c.category_id
GROUP BY c.category_id, c.category_name
ORDER BY units_sold DESC;

--  Number of Products in Each Category
SELECT 
    c.category_id,
    c.category_name,
    COUNT(p.product_id) AS total_products
FROM category c
LEFT JOIN product p ON c.category_id = p.category_id
GROUP BY c.category_id, c.category_name
ORDER BY total_products DESC;

--  Profit by Category
SELECT 
    c.category_id,
    c.category_name,
    SUM((oi.price_at_purchase - p.cost_price) * oi.quantity) AS total_profit
FROM order_items oi
JOIN product p ON oi.product_id = p.product_id
JOIN category c ON p.category_id = c.category_id
GROUP BY c.category_id, c.category_name
ORDER BY total_profit DESC;


/* CUSTOMER ANALYTIC */

--  Top Customers by Spending
SELECT 
    cu.cust_id,
    cu.first_name,
    cu.last_name,
    SUM(oi.quantity * oi.price_at_purchase) AS total_spent
FROM customers cu
JOIN orders o ON cu.cust_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY cu.cust_id, cu.first_name, cu.last_name
ORDER BY total_spent DESC;

--  Customer Order Count
SELECT 
    cu.cust_id,
    cu.first_name,
    cu.last_name,
    COUNT(o.order_id) AS total_orders
FROM customers cu
JOIN orders o ON cu.cust_id = o.customer_id
GROUP BY cu.cust_id, cu.first_name, cu.last_name
ORDER BY total_orders DESC;

--  Active vs Inactive Customers
SELECT 
    is_active,
    COUNT(*) AS customer_count
FROM customers
GROUP BY is_active;

--  Membership Type Distribution
SELECT 
    membership_type,
    COUNT(*) AS total_customers
FROM customers
GROUP BY membership_type
ORDER BY total_customers DESC;

--  Revenue by Membership Type
SELECT 
    cu.membership_type,
    SUM(oi.quantity * oi.price_at_purchase) AS revenue
FROM customers cu
JOIN orders o ON cu.cust_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY cu.membership_type
ORDER BY revenue DESC;

--  Average Customer Spend
SELECT 
    AVG(customer_spend) AS avg_customer_spend
FROM (
    SELECT 
        cu.cust_id,
        SUM(oi.quantity * oi.price_at_purchase) AS customer_spend
    FROM customers cu
    JOIN orders o ON cu.cust_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY cu.cust_id
) AS customer_totals;

--  Customers with No Orders
SELECT 
    cu.cust_id,
    cu.first_name,
    cu.last_name
FROM customers cu
LEFT JOIN orders o ON cu.cust_id = o.customer_id
WHERE o.order_id IS NULL;


/* ORDER ANALYSIS */

--  Order Value for Each Order
SELECT 
    o.order_id,
    o.customer_id,
    SUM(oi.quantity * oi.price_at_purchase) AS order_value
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.order_id, o.customer_id
ORDER BY order_value DESC;

--  Average Items per Order
SELECT 
    AVG(order_qty) AS avg_items_per_order
FROM (
    SELECT 
        order_id,
        SUM(quantity) AS order_qty
    FROM order_items
    GROUP BY order_id
) AS order_summary;

--  Orders by Status
SELECT 
    status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY status;

--  Top 10 Highest Value Orders
SELECT 
    o.order_id,
    o.customer_id,
    SUM(oi.quantity * oi.price_at_purchase) AS order_value
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.order_id, o.customer_id
ORDER BY order_value DESC
LIMIT 10;


/* PAYMENT ANALYTICS */

--  Payment Status Breakdown
SELECT 
    payment_status,
    COUNT(*) AS total_transactions
FROM payments
GROUP BY payment_status;

--  Payment Method Usage
SELECT 
    payment_mode,
    COUNT(*) AS transaction_count
FROM payments
GROUP BY payment_mode
ORDER BY transaction_count DESC;

--  Revenue by Payment Mode (successful only)
SELECT 
    payment_mode,
    SUM(amount) AS revenue
FROM payments
WHERE payment_status = 'Successful'
GROUP BY payment_mode
ORDER BY revenue DESC;

--  Failed Payments Count
SELECT 
    COUNT(*) AS failed_payments
FROM payments
WHERE payment_status = 'Failed';

--  Refund Count
SELECT 
    COUNT(*) AS refunded_transactions
FROM payments
WHERE payment_status = 'Refunded';


/* RETURNS ANALYSIS */

--  Total Returns
SELECT 
    COUNT(*) AS total_returns
FROM returns;

--  Return Status Breakdown
SELECT 
    return_status,
    COUNT(*) AS total_returns
FROM returns
GROUP BY return_status;

--  Return Reasons Breakdown
SELECT 
    return_reason,
    COUNT(*) AS frequency
FROM returns
GROUP BY return_reason
ORDER BY frequency DESC;

--  Total Returned Quantity
SELECT 
    SUM(returned_quantity) AS total_returned_units
FROM returns;

--  Total Return Amount
SELECT 
    SUM(return_amount) AS total_return_amount
FROM returns;

--  Return Rate (% of order items returned)
SELECT 
    ROUND(
        (SELECT COUNT(*) FROM returns) * 100.0 / 
        (SELECT COUNT(*) FROM order_items), 2
    ) AS return_rate_percent;

--  Most Returned Products
SELECT 
    p.product_id,
    p.product_name,
    COUNT(r.return_id) AS return_count,
    SUM(r.returned_quantity) AS total_returned_qty
FROM returns r
JOIN order_items oi ON r.order_item_id = oi.order_item_id
JOIN product p ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_returned_qty DESC;


/*  SUPPLIER ANALYSIS */

--  Number of Products Supplied by Each Supplier
SELECT 
    s.supplier_id,
    s.supplier_name,
    COUNT(p.product_id) AS total_products_supplied
FROM suppliers s
LEFT JOIN product p ON s.supplier_id = p.supplier_id
GROUP BY s.supplier_id, s.supplier_name
ORDER BY total_products_supplied DESC;

--  Revenue Contribution by Supplier
SELECT 
    s.supplier_id,
    s.supplier_name,
    SUM(oi.quantity * oi.price_at_purchase) AS supplier_revenue
FROM suppliers s
JOIN product p ON s.supplier_id = p.supplier_id
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY s.supplier_id, s.supplier_name
ORDER BY supplier_revenue DESC;

--  Profit Contribution by Supplier
SELECT 
    s.supplier_id,
    s.supplier_name,
    SUM((oi.price_at_purchase - p.cost_price) * oi.quantity) AS supplier_profit
FROM suppliers s
JOIN product p ON s.supplier_id = p.supplier_id
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY s.supplier_id, s.supplier_name
ORDER BY supplier_profit DESC;


/* STOCK ANALYSIS */

--  Current Inventory Value at Cost Price
SELECT 
    SUM(stock_quantity * cost_price) AS inventory_value_cost
FROM product;

--  Current Inventory Value at Selling Price
SELECT 
    SUM(stock_quantity * price) AS inventory_value_selling
FROM product;

--  Out-of-Stock Products
SELECT 
    product_id,
    product_name
FROM product
WHERE stock_quantity = 0;

--  Active vs Inactive Products
SELECT 
    is_active,
    COUNT(*) AS product_count
FROM product
GROUP BY is_active;


/*  STORE & EMPLOYEE ANALYSIS    */

--  Number of Employees per Store
SELECT 
    s.store_id,
    s.store_name,
    COUNT(e.emp_id) AS employee_count
FROM stores s
LEFT JOIN employees e ON s.store_id = e.store_id
GROUP BY s.store_id, s.store_name
ORDER BY employee_count DESC;

--  Average Salary by Designation
SELECT 
    designation,
    AVG(salary) AS avg_salary
FROM employees
GROUP BY designation
ORDER BY avg_salary DESC;

--  Active vs Inactive Employees
SELECT 
    is_active,
    COUNT(*) AS employee_count
FROM employees
GROUP BY is_active;

--  Store Opening Year Distribution
SELECT 
    YEAR(opening_date) AS opening_year,
    COUNT(*) AS stores_opened
FROM stores
GROUP BY YEAR(opening_date)
ORDER BY opening_year;
